// Code generated by go-bindata.
// sources:
// src/logic.nolol
// src/math.nolol
// src/string.nolol
// DO NOT EDIT!

package stdlib

import (
	"github.com/elazarl/go-bindata-assetfs"
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name    string
	size    int64
	mode    os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _logicNolol = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x6c\x91\xc1\x72\xd3\x4c\x10\x84\xef\x7a\x8a\xfe\x5d\xa9\x8a\xfd\x23\xa3\x98\x23\xc1\xdc\x73\xa5\xe0\x9c\xda\x95\x46\xd6\x14\xd2\x8c\x6a\x76\x96\x84\xb7\xa7\x76\x4d\x8c\x13\xb8\xee\x76\x75\x7f\xd3\xdd\x75\xf8\x3a\x71\xc2\xc8\x33\xa1\x57\xf1\xc0\x92\x10\x43\xe2\x1e\x03\x8d\x2c\xec\xac\x92\x10\x64\xc0\x12\x7a\xd3\x84\x51\x0d\xb3\x9e\xb8\xdf\xeb\x4a\x16\xea\x7f\xd3\x75\x78\x58\x56\x35\x47\x4e\x2c\x27\xdc\x82\xa5\x9f\xf3\x40\xd8\x24\x1f\xba\xaa\xdf\xe0\xb6\x29\xc2\x2f\xe4\xd9\x8a\x27\x78\x2c\x99\x43\xcd\x00\x27\xb8\x65\x6a\xa1\x3e\x91\x3d\x71\x22\xc4\x22\xbf\x28\x5a\x84\xca\x11\xb1\xe4\xe4\x88\x04\xc9\x4b\x24\x4b\xef\xaf\x5c\x5e\xbe\xee\xa0\x86\x43\x53\x99\xcf\xb8\x8f\x4e\x26\xc1\x7e\x6e\xaf\x0d\x5b\xc4\x1d\xe8\x79\xb5\x06\x00\x22\xde\x61\x1b\xf6\x71\xf7\xff\x45\xd3\x90\x0c\x95\xfa\xe1\x0d\xeb\x5d\x8b\xd5\x74\xc8\x3d\x95\x4b\x2c\x8b\xf3\x42\x7b\x32\x53\x83\x4f\xc1\xf1\xc4\xf3\x8c\xf4\x9d\x57\xf8\x44\x30\x5a\x02\x4b\xa9\x66\x66\xa1\x62\xf8\x2d\x85\x13\x7d\xc4\xe6\x0c\x57\xba\x67\xc9\xf4\x58\xbe\xb7\x3f\x82\xed\xee\x31\xe8\xf1\x70\x8f\xe4\x79\x1c\x8f\x1f\x70\xb3\x69\xea\x5a\x84\x9b\x92\xcf\xb5\xee\x20\x0e\x57\x88\xfa\xef\x28\x55\x2c\xb9\x9f\x5e\x1d\xfe\xda\xfb\x72\xc5\xee\x13\x9f\x44\x8d\x3e\x9f\x91\x4a\x01\xe7\x87\xee\xf8\xf7\xf9\x2f\xa3\x1d\xca\x68\xa1\x94\x1b\xff\x2c\x16\xb3\x57\x84\xa8\x3e\x15\xf1\xdb\x9d\xfe\x31\xc6\xb3\xda\x36\xb4\xd7\xe5\x07\xfc\x77\x44\x2c\x81\xbf\x02\x00\x00\xff\xff\xd2\xa5\x56\x4f\x95\x02\x00\x00")

func logicNololBytes() ([]byte, error) {
	return bindataRead(
		_logicNolol,
		"logic.nolol",
	)
}

func logicNolol() (*asset, error) {
	bytes, err := logicNololBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "logic.nolol", size: 661, mode: os.FileMode(438), modTime: time.Unix(1618428546, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _mathNolol = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x92\x4f\x8f\xd3\x30\x10\xc5\xcf\xf6\xa7\x78\xac\xb4\xda\xa6\xff\x92\x14\x24\x38\x6c\xf6\xbe\x57\x84\xc4\x8d\x95\x9d\x4c\x9a\x51\x53\xbb\xd8\x13\xea\x8f\x8f\x9c\x2e\x4b\xa9\x90\x10\x17\x5b\xf1\xcc\x7b\xbf\x3c\x7b\xca\x12\x5f\x06\x8e\xe8\x79\x24\xb4\xde\x89\x61\x17\x61\x4d\xe4\x16\x1d\xf5\xec\x58\xd8\xbb\x08\xe3\x3a\x1c\x4d\x1b\x7c\x44\xef\x03\x8e\x46\x06\x5d\x96\x78\x3e\x9e\x7c\x10\x4c\x91\xdd\x1e\x0f\x60\xd7\x8e\x53\x47\xb8\x8b\xd2\x95\xb9\xe7\x0e\x0f\x5a\xcf\x0c\x9a\x35\x74\x34\xc2\xad\x19\x33\x2a\x8a\x71\x82\x13\xeb\x99\x73\xa9\xbf\x9c\xb8\x79\xbf\xad\x3f\xd4\xff\x50\xd1\x1f\x22\x6a\x76\xdb\x8f\xf5\xa7\x59\xf3\x99\x64\x0a\x2e\x42\x06\x82\xb1\xd1\x8f\x93\x10\x7e\x98\x71\x22\xf8\x1e\x69\x9b\x7b\xbe\xfa\x70\x88\xf0\x0e\xe6\x92\x74\xd3\x0e\x7c\xd2\x73\xbc\x8b\xa1\xb1\xf1\x65\xae\x2c\x52\x01\x4a\xa7\xa0\xd5\x22\x3d\x35\x55\xb1\x4c\x9b\x45\x7a\xcc\xbb\x26\xd7\xcd\xc0\xe7\x1e\x09\x1c\xf1\x54\xad\x11\x5e\xe1\x35\xb8\xc7\x63\xf5\xfa\x8d\x4d\xbd\x86\x97\x81\xc2\x99\x23\xbd\x35\x55\xd7\xc4\xc8\x7b\x77\x0b\xcb\xa8\xa6\x2a\xde\x48\xd7\xd1\x1c\x25\xc1\xe8\xcf\x14\xc0\x4e\x68\x4f\x01\xe2\x91\x2e\x6d\xdf\x27\x0e\x14\x61\x04\x23\x99\x28\xbf\x62\xe2\x36\x66\x3f\x7a\x1f\x7e\x53\xd3\x26\xdd\xd7\xff\x45\xbb\xf5\xba\xbd\xb4\x54\xd6\x55\x55\x2d\xf3\xf2\x57\x5f\xcb\x32\x5f\x49\xf2\x21\xbf\x8e\x99\xc7\xcc\x82\x1d\xfc\x24\xd7\xee\xc9\x87\x85\x59\xc3\xae\x73\xa1\x80\x1d\x7d\x7b\xd0\xca\x4f\xd2\x54\x5a\xb5\x12\xf2\x76\x1e\xf2\x0c\xd7\xe8\xbc\x56\xb9\xb4\x6a\x16\xe6\x7e\xf7\xae\xb1\xf7\xbb\x62\xb9\xfb\xd6\x4a\x58\xad\xa0\x95\x32\xcd\x55\x78\x53\xee\x0a\xad\x94\xbd\x3e\xb3\x97\x33\xee\x61\x56\xb6\x69\xaa\xfc\xab\x4e\x2b\xa5\x6c\x20\x73\xc8\x16\x39\xcb\xbc\x90\xeb\x7e\x06\x00\x00\xff\xff\xbf\xbb\xa8\x65\x42\x03\x00\x00")

func mathNololBytes() ([]byte, error) {
	return bindataRead(
		_mathNolol,
		"math.nolol",
	)
}

func mathNolol() (*asset, error) {
	bytes, err := mathNololBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "math.nolol", size: 834, mode: os.FileMode(438), modTime: time.Unix(1618592198, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

var _stringNolol = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\x94\x91\xc1\xae\x94\x40\x10\x45\xf7\x7c\xc5\x1d\x36\xcf\x97\x11\x89\x1f\x80\x89\x4b\xb7\xc6\xbd\x69\xa1\x80\x4a\xa0\xba\x53\x55\x4c\xf8\x7c\xd3\x0d\x33\x71\xc6\xb8\x70\x49\x71\xeb\x9e\x53\xe9\xb6\xc5\x8f\x99\x0d\x23\x2f\x84\x3e\x8a\x07\x16\xc3\xaf\x60\xdc\x63\xa0\x91\x85\x9d\xa3\x18\x82\x0c\x58\x43\xaf\xd1\x30\x46\x85\xb9\xb2\x4c\xcd\x1a\x84\xd3\xb6\x84\x9c\xa9\xda\x16\xdf\xd6\x14\xd5\xb1\x19\xcb\x84\x37\xb0\xf4\xcb\x36\x10\x6a\xf3\xa1\x3d\x56\x6a\xbc\x55\x39\xf9\x9d\xd6\x78\x23\x83\xcf\x84\x25\x98\xa3\x9f\x83\x86\xde\x49\x31\x6a\x5c\x33\xa0\x30\x95\x7c\x53\x31\xb0\x57\x05\x7f\x92\x7f\xa6\x98\x3e\x98\xeb\x3b\x68\x4f\x5a\x01\xc8\x3f\x9a\xa6\x31\xd7\x8a\x64\x38\x19\xc7\xee\x67\xf0\x58\x0a\x1f\xf7\xed\xcf\x65\xf7\x79\x6e\xfc\xb8\xbf\x74\xee\x97\xee\xcf\xd2\xaf\xc3\x70\x5a\x93\x4c\xb3\x23\x1e\xd5\x1e\x11\x37\xcf\x81\xfc\xc5\x06\x23\xcf\xc3\xba\x06\x4b\xc9\x27\x8d\x3d\x99\x3d\x93\x17\x92\x02\xcd\xcb\xef\x58\x58\xa8\x70\x67\x52\xfa\x72\xb7\xbe\x74\xb9\xc5\x67\x92\xe3\xc6\x9c\xbd\x5e\x31\x45\x8f\x25\x88\xac\xf6\xd0\x4b\x89\xe4\x34\x54\xba\x91\x1a\x3d\x2b\x7e\xfa\x6f\xc7\xb3\xa6\x78\xfe\x5b\xf3\xd2\xdd\x25\xb3\x5e\xf7\xfa\x4c\x7f\xd9\xfe\x0e\x00\x00\xff\xff\x15\x54\x89\x18\x79\x02\x00\x00")

func stringNololBytes() ([]byte, error) {
	return bindataRead(
		_stringNolol,
		"string.nolol",
	)
}

func stringNolol() (*asset, error) {
	bytes, err := stringNololBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "string.nolol", size: 633, mode: os.FileMode(438), modTime: time.Unix(1618428089, 0)}
	a := &asset{bytes: bytes, info: info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if err != nil {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"logic.nolol": logicNolol,
	"math.nolol": mathNolol,
	"string.nolol": stringNolol,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func     func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"logic.nolol": &bintree{logicNolol, map[string]*bintree{}},
	"math.nolol": &bintree{mathNolol, map[string]*bintree{}},
	"string.nolol": &bintree{stringNolol, map[string]*bintree{}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
	data, err := Asset(name)
	if err != nil {
		return err
	}
	info, err := AssetInfo(name)
	if err != nil {
		return err
	}
	err = os.MkdirAll(_filePath(dir, filepath.Dir(name)), os.FileMode(0755))
	if err != nil {
		return err
	}
	err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
	if err != nil {
		return err
	}
	err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
	if err != nil {
		return err
	}
	return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
	children, err := AssetDir(name)
	// File
	if err != nil {
		return RestoreAsset(dir, name)
	}
	// Dir
	for _, child := range children {
		err = RestoreAssets(dir, filepath.Join(name, child))
		if err != nil {
			return err
		}
	}
	return nil
}

func _filePath(dir, name string) string {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}


func assetFS() *assetfs.AssetFS {
	assetInfo := func(path string) (os.FileInfo, error) {
		return os.Stat(path)
	}
	for k := range _bintree.Children {
		return &assetfs.AssetFS{Asset: Asset, AssetDir: AssetDir, AssetInfo: assetInfo, Prefix: k}
	}
	panic("unreachable")
}
